// SERVER CONSTANTS
var KATALON_SERVER_URL_PREFIX = "http://localhost:";
var KATALON_SERVER_URL_SUFFIX = "/"
var XHTTP_GET_METHOD = "GET";
var XHTTP_POST_METHOD = "POST";
var XHTTP_ACTION = "xhttp";
var POST_DOM_MAP_SUCCESS = "Load DOM map to Katalon successfully"
	
// COMMAND CONSTANTS
var START_ADDON = "START_ADDON";
var STOP_ADDON = "STOP_ADDON";
var REQUEST_BROWSER_INFO = "REQUEST_BROWSER_INFO";
var BROWSER_INFO = "BROWSER_INFO";
var CHECK_ADDON_START_STATUS = "CHECK_ADDON_START_STATUS";
var START_INSPECT = "START_INSPECT";
var START_RECORD = "START_RECORD";
var HIGHLIGHT_OBJECT = "HIGHLIGHT_OBJECT";

// RUN MODE CONSTANTS
var RUN_MODE_IDLE = "RUN_MODE_IDLE";
var RUN_MODE_OBJECT_SPY = "RUN_MODE_OBJECT_SPY";
var RUN_MODE_RECORDER = "RUN_MODE_RECORDER";

// BROWSER CONSTANTS
var CHROME = "Chrome";

// STYLE CONSTANTS
var ELEMENT_HOVER_OUTLINE_STYLE = "2px solid #f00";

// ANIMATION CONSTANTS
var ELEMENT_FLASHING_OUTLINE_STYLE = "2px solid #0F0"
var ELEMENT_FLASHING_OUTLINE_COLOR_1 = "#FFF";
var ELEMENT_FLASHING_OUTLINE_COLOR_2 = "#0F0";
var ELEMENT_FLASHING_OUTLINE_COLOR_3 = "#F00";